frontend/src/App.js, frontend/src/components/Login_modal.css, frontend/src/components/Login_modal.js, frontend/src/components/Signup.css, frontend/src/components/Signup.js, frontend/src/components/Start_nav.js, frontend/src/pages/Start_page.css, frontend/src/pages/Start_page.js
=> 로그인, 회원가입 페이지 생성

frontend/src/App.css, frontend/src/App.js, frontend/src/components/NewLog_modal.js, frontend/src/components/Sidebar.js, frontend/src/pages/Home.js, frontend/src/pages/Log_list.js, frontend/src/pages/Search.js
- 사이드 바의 '내 회의록' 하위 폴더 클릭 시 나타날 페이지
- 화면 구성이 똑같은 검색 페이지도 만들었음
=> 회의록 목록 페이지 구현

frontend/src/App.css, frontend/src/components/AddParticipant.js, frontend/src/components/NewLog_modal.js
- 참가자 버튼 기능 구현
- css 보완 필요
- 추가버튼 클릭 시 입력값이 input에 남아있음
=> 새 회의록 모달 수정

frontend/src/components/Find_pwModal.js, frontend/src/components/LoginModal.js, frontend/src/components/LogoutGoogle.js, frontend/src/pages/Start.js
구글 로그인, 로그아웃 기능만 가능
실질적인 구현은 X
비밀번호 찾기 질문 필요
=> 구글 로그인, 로그아웃 버튼

frontend/public/index.html, frontend/src/App.css, frontend/src/App.js, frontend/src/api/axios.js, frontend/src/components/Footer.js, frontend/src/components/Header.js, frontend/src/components/LoginModal.js, frontend/src/components/Sidebar.js, frontend/src/components/Sidebar_log.js, frontend/src/components/SignupModal.js, frontend/src/components/Start_nav.js, frontend/src/pages/Home.js, frontend/src/pages/Start.js
=> Revert "사이드바/홈 수정"

frontend/package.json, frontend/src/components/NewLog_modal.js, frontend/src/components/Sidebar.js, frontend/src/components/Signup/SignupModal.js, frontend/src/pages/Home.js, frontend/src/pages/Log_list.js, frontend/src/pages/New_log.js
/loglist 에서 회의록 정보 받기
package.json에 CORS 충돌 방지로 프록시 추가
=> 회의록 정보 생성(참가자 정보는 X)

frontend/src/App.css, frontend/src/api/axios.js, frontend/src/components/Log_card.js, frontend/src/components/Signup/SignupModal.js, frontend/src/pages/Home.js, frontend/src/pages/Log_list.js
Log_card.js 추가 - Home, Log_list 페이지에서 회의록 정보 출력
axios.js 수정 - 상황에 따라 헤더값 바뀌도록 수정
SignupModal.js 수정 - 닉네임 중복 확인 기능 추가
※모든 회의록 정보를 받아오기 때문에 조건에 맞게 출력 필요
=> 회의록 정보 화면 출력

backend_django/user/views.py, frontend/src/App.js, frontend/src/components/Log_card.js, frontend/src/components/NewLog_modal.js, frontend/src/components/Sidebar.js, frontend/src/components/Sidebar_log.js, frontend/src/pages/Home.js, frontend/src/pages/Log.js, frontend/src/pages/Log_list.js
- 추가/수정/삭제 다 가능
-New_log.js -> Log.js 파일명 변경
- /:dr_id/:dr_name/:mn_id/log로 새 회의록 주소 변경
- newlog_modal->log.js url로 데이터 전달
- log_card 클릭 시 log.js로 연결
- 회의록 사이드바에 회의 정보 출력
=> 디렉토리 에러 수정

frontend/src/App.css, frontend/src/components/Sidebar.js, frontend/src/pages/Profile.js
프로필 사진 선택 후 저장 or 삭제
저장시 프로필 사진 변경(서버와 통신은 아직 X),
삭제 시 기본 이미지로 설정
=> 프로필 사진 변경 기능

backend_django/backend_django/urls.py, backend_django/minute/file_urls.py, backend_django/minute/minutes_urls.py, backend_django/minute/models.py, backend_django/minute/serializers.py, backend_django/minute/views.py
@mui/material @emotion/react @emotion/styled @mui/icons-material 설치
회의록 수정 클릭시 메모 저장
북마크 목록 불러오기 및 삭제 가능
=> 북마크 목록 불러오기 및 삭제

frontend/src/App.css, frontend/src/components/Header_log.js, frontend/src/components/NewLog_modal.js, frontend/src/components/Sidebar.js, frontend/src/components/Sidebar_log.js, frontend/src/pages/Log.js
- 회의록 생성 모달: 참가자 수 입력창 -> 회의장소 입력으로 변경
- sidebar_log: 참가자 정보 -> 회의 장소 정보
- log.js: 파일 업로드 버튼 클릭 시 참가자 수 입력 먼저 받고 파일 업로드
- header_log.js 추가(현재는 그냥 헤더랑 큰 차이x)
=> 참가자 수 입력 수정

frontend/src/components/Sidebar.js, frontend/src/components/Sidebar_log.js, frontend/src/components/Signup/SignupModal.js
=> 회원가입 시 디렉토리 생성

frontend/src/components/EditLog_modal.js, frontend/src/components/Login/LoginModal.js, frontend/src/components/Sidebar_log.js, frontend/src/components/Signup/SignupModal.js, frontend/src/pages/Log.js
회의록 제목, 장소, 시간, 메모 수정 기능 추가
키워드 형식 추가(추후 기능구현 필요)
구글 로그인 기능 안보이게 변경
=> 회의록 정보 수정 기능 추가

backend_django/voice_recognition/urls.py, backend_django/voice_recognition/views.py, frontend/src/App.css, frontend/src/App.js, frontend/src/components/EditLog_modal.js, frontend/src/components/NewLog_modal.js, frontend/src/components/Sidebar_log.js, frontend/src/components/Signup/SignupModal.js, frontend/src/pages/Emotion.js, frontend/src/pages/Log.js, frontend/src/pages/Start.js, frontend/src/pages/Summary.js
- voice/recognition/lists/<int:mn_id> (get, post)
- stt 전체 결과 출력
- 키워드/요약 페이지 제작
- start.js에 프로필 정보 받아올 때,  회원가입 후 디렉토리 추가할 때 if문 추가
=> 음성 인식 api url 수정

frontend/package-lock.json, frontend/package.json, frontend/src/pages/Log.js
npm i react-highlight-words 설치
검색어에 해당되는 회의내용 하이라이트
=> 회의내용 검색 구현

frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/App.js, frontend/src/components/Sidebar.js, frontend/src/components/bookmark.js, frontend/src/pages/Emotion.js, frontend/src/pages/Favorite.js, frontend/src/pages/Home.js, frontend/src/pages/Log.js
- npm i react-scroll
- 북마크 클릭 시 그 대화가 맨 위인 위치로 이동; dialogue 요소에 스크롤이 생길만큼 길어야 함, 스크롤 되는 만큼만 이동됨
- 메모 아래에 저장 버튼 추가
- 감정분석 페이지에 사용자 이름, 회의 제목 추가
- home.js 기본 디렉토리 수정
- 즐겨찾기 페이지 제작(아직은 모든 회의록 출력 중)
=> 북마크, 채팅창 연결

frontend/src/App.css, frontend/src/pages/Emotion.js, frontend/src/pages/Log.js
- 참가자 이름/대화 수정 구현
- 파일 업로드 에러 -> stt 호출x
=> 참가자 이름, 대화 수정

frontend/src/pages/Home.js, frontend/src/pages/Log.js
Home.js에 회의록 태도 변화 그래프 추가
Log.js의 모달 에러 수정(모달이 동시에 뜨는 오류 수정)
=> 회의록 태도 변화 그래프 추가,모달 에러 수정

frontend/src/App.css, frontend/src/pages/Emotion.js, frontend/src/pages/Log.js, frontend/src/pages/Summary.js
- 인식 결과 이모지로 표현
- 감정별 출력
- 키워드/요약 출력
=> 감정인식, 키워드/요약

frontend/src/pages/Log.js
=> spinner 보여주기

frontend/src/App.css, frontend/src/pages/Emotion.js, frontend/src/pages/Home.js, frontend/src/pages/Summary.js
- 데이터 출력
- 내용정리 페이지: speaker_seq없으면 뒤로 돌아가기
=> 최근 회의록 5개 차트
